openapi: 3.0.0
info:
  title: Product Service API
  description: API for managing products in ChoreoCart application
  version: 1.0.0
servers:
  - url: /
paths:
  /products:
    get:
      summary: Get all products
      description: Retrieves the list of all available products
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Get product by ID
      description: Retrieves a specific product by its ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
  /products/search:
    get:
      summary: Search products
      description: Search products by name or category
      parameters:
        - name: query
          in: query
          schema:
            type: string
          description: Search term
        - name: category
          in: query
          schema:
            type: string
          description: Category filter
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the product
        name:
          type: string
          description: Name of the product
        description:
          type: string
          description: Detailed description of the product
        price:
          type: number
          format: float
          description: Price of the product
        imageUrl:
          type: string
          description: URL to the product image
        category:
          type: string
          description: Product category
        stock:
          type: integer
          description: Available quantity in stock
      required:
        - id
        - name
        - price