openapi: 3.0.0
info:
  title: Cart Service API
  description: API for managing shopping cart in ChoreoCart application
  version: 1.0.0
servers:
  - url: /
paths:
  /cart:
    get:
      summary: Get cart contents
      description: Retrieves the current contents of the shopping cart
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'
        '405':
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add item to cart
      description: Adds a new product to the shopping cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItem'
      responses:
        '201':
          description: Item added successfully
        '400':
          description: Invalid request body or missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Clear cart
      description: Removes all items from the shopping cart
      responses:
        '200':
          description: Cart cleared successfully
        '405':
          description: Method not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CartItem:
      type: object
      properties:
        id:
          type: integer
          description: Product ID
        name:
          type: string
          description: Product name
        price:
          type: number
          format: float
          description: Product price
      required:
        - id
        - name
        - price
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error